#!/bin/sh
# 
# Author: Bill Mills
#
#
# Copyright (c) 2013, Yahoo! Inc.  All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License"). You may
# obtain a copy of the License at http://www.apache.org/licenses/LICENSE-2.0.
# See accompanying LICENSE file for terms.
#


export OUTFILE=$1
export configpath=../config 

if test -z "$OUTFILE"  
then
    echo "No filename specified."
    exit 1
fi

function import () {
    local filename
    filename=$configpath/$1
    local varname=$2

    echo ""
    echo "/*"
    echo "** $varname imported from $filename"
    echo "*/"
    echo -n "#define"  $2 "("
    sed -e 's/"/\\"/g' -e 's/^/"/' -e 's/$/"\\/' < $filename
    echo 
    echo ")"
}

(
cat <<EOF
/*
 * Copyright (c) 2013, Yahoo! Inc.  All rights reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License"). You may
 * obtain a copy of the License at http://www.apache.org/licenses/LICENSE-2.0.
 * See accompanying LICENSE file for terms.
 */
/*
** Generated by import_sql.sh
**
** Do not edit manually, this file should be built
** automatically as part of the make process.
**
*/
EOF

import db_schema.sql SQL_DB_SCHEMA 
import db_clear.sql SQL_DB_CLEAR
import unit_test_data.sql SQL_DB_UNIT_TESTS_DATA 
) >$OUTFILE