/*
 * Copyright (c) 2013, Yahoo! Inc.  All rights reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License"). You may
 * obtain a copy of the License at http://www.apache.org/licenses/LICENSE-2.0.
 * See accompanying LICENSE file for terms.
 */
/*
** Generated by import_sql.sh
**
** Do not edit manually, this file should be built
** automatically as part of the make process.
**
*/

/*
** SQL_DB_SCHEMA imported from ../config/db_schema.sql
*/
#define SQL_DB_SCHEMA ("/*"\
"** Author: Bill Mills"\
"**"\
" * Copyright (c) 2013, Yahoo! Inc.  All rights reserved."\
" *"\
" * Licensed under the Apache License, Version 2.0 (the \"License\"). You may"\
" * obtain a copy of the License at http://www.apache.org/licenses/LICENSE-2.0."\
" * See accompanying LICENSE file for terms."\
"**"\
"** DB scheme for the SQLite credential store database."\
"**"\
"** XXXXXXX Need to sort out where we will actually put the database file."\
"*/"\
""\
""\
"BEGIN;"\
""\
"CREATE TABLE IF NOT EXISTS creds ("\
"	identity INTEGER NOT NULL,"\
"	scheme NOT NULL,"\
"	token  NOT NULL,"\
"	secret,"\
"	session,"\
"	expiry INTEGER,"\
"	PRIMARY KEY (identity, scheme),"\
"	FOREIGN KEY (identity) REFERENCES identities (ROWID)"\
");"\
""\
"CREATE TABLE IF NOT EXISTS identities ("\
"    	username,"\
"    	realm,"\
"    	scope,"\
"    	authentication_url,"\
"    	refresh_url,"\
"    	initiate_url,"\
"	PRIMARY KEY (username, realm, scope)"\
");"\
""\
"CREATE TABLE IF NOT EXISTS endpoints ("\
"  	realm,"\
"	username,"\
"  	hostname,"\
"  	port INTEGER,"\
"  	path,"\
"	identity INTEGER,"\
"	PRIMARY KEY (username, hostname, port),"\
"	FOREIGN KEY (identity) REFERENCES identities (ROWID)"\
");"\
""\
"CREATE TABLE IF NOT EXISTS config ("\
"	name UNIQUE NOT NULL,"\
"	value INTEGER,"\
"	text,"\
"	PRIMARY KEY (name)"\
");"\
""\
"REPLACE INTO config VALUES ('version', 0, '');"\
""\
"COMMIT;"\
)

/*
** SQL_DB_CLEAR imported from ../config/db_clear.sql
*/
#define SQL_DB_CLEAR ("/*"\
"** Author: Bill Mills"\
"** Copyright Yahoo! Inc., 2011"\
"**"\
"** DB scheme for the SQLite credential store database."\
"**"\
"** XXXXXXX Need to sort out where we will actually put the database file."\
"*/"\
""\
""\
"BEGIN;"\
""\
"DROP TABLE IF EXISTS creds;"\
"DROP TABLE IF EXISTS identities;"\
"DROP TABLE IF EXISTS endpoints;"\
""\
"COMMIT;"\
)

/*
** SQL_DB_UNIT_TESTS_DATA imported from ../config/unit_test_data.sql
*/
#define SQL_DB_UNIT_TESTS_DATA ("/*"\
"** Author: Bill Mills"\
"** "\
" * Copyright (c) 2013, Yahoo! Inc.  All rights reserved."\
" *"\
" * Licensed under the Apache License, Version 2.0 (the \"License\"). You may"\
" * obtain a copy of the License at http://www.apache.org/licenses/LICENSE-2.0."\
" * See accompanying LICENSE file for terms."\
"**"\
"** DB scheme for the SQLite credential store database."\
"**"\
"*/"\
""\
""\
"BEGIN;"\
""\
"INSERT INTO identities VALUES ('user@example.com', 'example.com', "\
"	'demo', 'http://login.example.com/',  "\
"	'http://login.example.com/token',"\
" 	'http://login.example.com/init');"\
""\
"INSERT INTO creds VALUES ("\
"	(SELECT ROWID FROM identities WHERE username == 'user@example.com' LIMIT 1), "\
"	'bearer', 'token_goes_here',  'i_am_a_secret',  'jam_session', 3600);"\
""\
"INSERT INTO endpoints VALUES ("\
"	'example.com', 'user@example.com', 'imap.example.com', 143,  '', "\
"	(SELECT ROWID FROM identities WHERE username == 'user@example.com' LIMIT 1)"\
"	);"\
""\
"COMMIT;"\
)
